# this code generates a plot of relative bias of the NP-TE, MLE-TE, and PSN estimators (Figure 2)

# this code assumes that R code in the following files has been run:
# TEcurveMC.R  (for the NP-TE estimator)
# pTEcurveMC.R  (for the MLE-TE estimator)

rm(list=ls(all=TRUE))

library(RCurl)
library(rstudioapi)

currentDir <- dirname(getSourceEditorContext()$path)

# source 'TEcurveMC_myFunctions.R'
script <- getURL("https://raw.githubusercontent.com/mjuraska/mCEPcurve-three-phase/master/TEcurveMC_myFunctions.R", ssl.verifypeer = FALSE)
eval(parse(text=script))

# the total sample size
n <- 5000

# the indicator of whether marker distributions are truncated
truncateMarker <- TRUE

# calculate the values of the probit risk model coefficients
beta2 <- -0.02
# the marginal probability of infection in the placebo group set to 0.1
beta0 <- getBeta0(beta2, meanS0=2, varS0=1, 0.1, scenario="A2", threshold=1.5)
beta1start <- startBeta1(beta0, 0.75)
beta3 <- getBeta3(beta0, beta1start, beta2, meanS1=3, varS1=1, 0.25)
# the marginal probability of infection in the vaccine group set to 0.05
beta1 <- getBeta1(beta0, beta2, beta3, meanS1=3, varS1=1, 0.05, scenario="A2", threshold=1.5)
beta <- c(beta0, beta1, beta2, beta3)

# the grid of marker values
s1 <- seq(1.5, qnorm(0.95, mean=3, sd=1), by=0.05)

# VE(s1) curve evaluated on the grid
trueVEcurve <- trueTE(s1, beta0, beta1, beta2, beta3, 2, 1, 3, 1, 0.7, scenario="A2", threshold=1.5)

# the number of Monte-Carlo iterations
nMC <- 1000

# a sampling probability for sampling a Phase 2/3 subcohort with biomarker measurements
pi <- c(0.1, 0.25, 0.5)

bias <- matrix(NA, nrow=length(s1), ncol=3*length(pi))
rBias <- matrix(NA, nrow=length(s1), ncol=3*length(pi))

for (i in 1:length(pi)){
  # a matrix named 'TE.MCestimates' generated by 'TEcurveMC.R'
  load(file.path(currentDir, paste0("TE_MCestimates_nMC=",nMC,"_N=",n,"_truncateMarker=",truncateMarker,"_pi=",pi[i],".RData")))
  
  bias[,i] <- rowMeans(TE.MCestimates, na.rm=TRUE) - trueVEcurve
  rBias[,i] <- 100*bias[,i]/trueVEcurve
  
  # a matrix named 'TE.MCestimates' generated by 'pTEcurveMC.R'
  load(file.path(currentDir, paste0("pTE_MCestimates_ns.df=3_nMC=",nMC,"_N=",n,"_truncateMarker=",truncateMarker,"_pi=",pi[i],".RData")))
  
  bias[,i+3] <- rowMeans(TE.MCestimates, na.rm=TRUE) - trueVEcurve
  rBias[,i+3] <- 100*bias[,i+3]/trueVEcurve
}

# add bias and relative bias of the PSN estimator of Huang (2017)
load(file.path(currentDir, "TEcurveMC_PSNestimator.Rdata"))

bias[,7] <- out.01$mean.psn.0 - trueVEcurve
bias[,8] <- out.025$mean.psn.0 - trueVEcurve
bias[,9] <- out.05$mean.psn.0 - trueVEcurve
rBias[,7] <- out.01$rel.bias.psn.0
rBias[,8] <- out.025$rel.bias.psn.0
rBias[,9] <- out.05$rel.bias.psn.0

# relative bias plot
cexTitle <- 1.5
cexLab <- 1.4
cexAxis <- 1.3
cexLegend <- 1.2
Col <- rep(c("black", "darkgoldenrod2", "magenta3"), each=3)
magFactor <- 0.65

for (i in 1:length(pi)){
  pdf(file.path(currentDir, paste0("plotRelBias_ns.df=3_",ifelse(truncateMarker,"truncated","nontruncated"),"Normal_pi=",pi[i],".pdf")), width=magFactor*6, height=magFactor*8)
  par(mar=c(4,5,1.5,0.4), cex.lab=cexLab, cex.axis=cexAxis, las=1)
  plot(0, 0, type="n", xlab=expression(s[1]), ylab="", xlim=range(s1), ylim=range(exp(rBias/100)), xaxt="n", yaxt="n")
  if (i==1){ mtext(expression(paste("Relative Bias of ",widehat(TE)(s[1]))), side=2, line=3.2, cex=cexLab, las=0) }
  mtext(substitute(pi==piValue, list(piValue=pi[i])), side=3, cex=cexTitle, line=0)
  axis(side=1, at=seq(1.5,4.5,by=1), cex.axis=cexAxis)
  axis(side=1, at=2:4, labels=format(c(2,3,4), nsmall=1, digits=1), cex.axis=cexAxis)
  axis(side=2, at=exp(seq(-0.1,-2.4,by=-0.1)), labels=FALSE, tcl=-0.3)
  axis(side=2, at=exp(seq(0,-2.5,by=-0.5)), labels=c(0,format(seq(-0.5,-2.5,by=-0.5), nsmall=1, digits=1)), cex.axis=cexAxis)
  abline(h=exp(0), col="gray50", lwd=2)
  
  for (j in c(i,i+3,i+6)){
    lines(s1, exp(rBias[,j]/100), lwd=3, lty="solid", col=Col[j])
  }
  
  if (i==1){
    legend("bottomright", lwd=3, col=c("black", "darkgoldenrod2", "magenta3"), legend=c("NP-TE", "MLE-TE", "PSN"),
           bty="n", cex=cexLegend)  
  }
  
  dev.off()
}

