# this code generates a plot of 95% CI coverage probabilities for the NP-TE, MLE-TE, and PSN estimators (Figure 4)

# this code assumes that R code in the following files has been run:
# TEcurveMC_coverageSizePower.R  (for the NP-TE estimator)
# pTEcurveMC_coverageSizePower.R  (for the MLE-TE estimator)

rm(list=ls(all=TRUE))

library(RCurl)
library(rstudioapi)

currentDir <- dirname(getSourceEditorContext()$path)

# source 'TEcurveMC_myFunctions.R'
script <- getURL("https://raw.githubusercontent.com/mjuraska/mCEPcurve-three-phase/master/TEcurveMC_myFunctions.R", ssl.verifypeer = FALSE)
eval(parse(text=script))

# the total sample size
n <- 5000

# the indicator of whether marker distributions are truncated
truncateMarker <- TRUE

# the grid of marker values
s1 <- seq(1.5, qnorm(0.95, mean=3, sd=1), by=0.05)

# the number of MC iterations
nMC <- 1000

# the number of bootstrap iterations within each MC iteration
nBoot <- 500

# a sampling probability for sampling a Phase 2 subcohort with biomarker measurements
pi <- c(0.1, 0.25, 0.5)

cover <- matrix(NA, nrow=length(s1), ncol=3*length(pi))
# these operating characteristics are unavailable for the PSN estimator of Huang (2017)
smCover <- rep(NA, 2*length(pi))

for (i in 1:length(pi)){
  # this file is generated by TEcurveMC_coverageSizePower.R
  fileName <- paste0("TE_coverSizePower_RoyBose_nMC=",nMC,"_N=",n,"_nBoot=",nBoot,"_truncateMarker=",truncateMarker,"_pi=",pi[i],".RData")
  # a list named 'inferenceVE'
  load(file.path(currentDir, fileName))
  
  coverInd <- do.call(cbind, lapply(inferenceVE, "[[", "coverInd"))
  smCoverInd <- do.call(c, lapply(inferenceVE, "[[", "smCoverInd"))
  
  
  cover[,i] <- rowMeans(coverInd, na.rm=TRUE)
  smCover[i] <- mean(smCoverInd, na.rm=TRUE)
  
  # this file is generated by pTEcurveMC_coverageSizePower.R
  fileName <- paste0("pTE_coverSizePower_RoyBose_ns.df=3_nMC=",nMC,"_N=",n,"_nBoot=",nBoot,"_truncateMarker=",truncateMarker,"_pi=",pi[i],".RData")
  # a list named 'inferenceVE'
  load(file.path(currentDir, fileName))
  
  coverInd <- do.call(cbind, lapply(inferenceVE, "[[", "coverInd"))
  smCoverInd <- do.call(c, lapply(inferenceVE, "[[", "smCoverInd"))
  
  
  cover[,i+3] <- rowMeans(coverInd, na.rm=TRUE)
  smCover[i+3] <- mean(smCoverInd)
}

# add coverage for the PSN estimator of Huang (2017)
load(file.path(currentDir, "TEcurveMC_PSNestimator.Rdata"))
cover[,7] <- out.01$CI.psn.0
cover[,8] <- out.025$CI.psn.0
cover[,9] <- out.05$CI.psn.0

# coverage plot
cexTitle <- 1.5
cexLab <- 1.4
cexAxis <- 1.3
cexLegend <- 1.2
Col <- rep(c("black", "darkgoldenrod2", "magenta3"), each=3)
magFactor <- 0.65

for (i in 1:length(pi)){
  pdf(file.path(currentDir, paste0("plotCover_",ifelse(truncateMarker,"truncated","nontruncated"),"Normal_pi=",pi[i],"_v2.pdf")), width=magFactor*6, height=magFactor*8)
  par(mar=c(4,5,1.5,0.4), cex.lab=cexLab, cex.axis=cexAxis, las=1)
  plot(0, 0, type="n", xlab=expression(s[1]), ylab="", xlim=range(s1), ylim=c(0.91,0.99), xaxt="n", yaxt="n")
  axis(side=1, at=seq(1.5,4.5,by=1), cex.axis=cexAxis)
  axis(side=1, at=2:4, labels=format(c(2,3,4), nsmall=1, digits=1), cex.axis=cexAxis)
  if(i==1){ mtext(expression(paste("Coverage of Pointwise 95% CI for ",TE(s[1]))), side=2, line=3.4, cex=cexLab, las=0) }
  mtext(substitute(pi==piValue, list(piValue=pi[i])), side=3, cex=cexTitle, line=0)
  axis(side=2, at=seq(0.9,1,by=0.01), cex.axis=cexAxis)
  abline(h=0.95, col="gray50", lwd=2)
  
  # MC error lines
  abline(h=0.95+c(-1,1)*qnorm(0.975)*sqrt(0.95*0.05/nMC), col="gray50", lty="dotted", lwd=2)
  
  for (j in c(i,i+3,i+6)){
    lines(s1, cover[,j], lwd=3, lty="solid", col=Col[j])
  }
  
  if (i==1){
    legend("bottomleft", lwd=3, col=c("black", "darkgoldenrod2", "magenta3"), legend=c("NP-TE", "MLE-TE", "PSN"),
           bty="n", cex=cexLegend)
  }

  dev.off()
}
